# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Test Charts

on:
  pull_request:
    types: [opened, synchronize]
  push:

permissions: { }

env:
  CT_IMAGE: quay.io/helmpack/chart-testing:v3.14.0
  DOCKER_COMMAND: docker run --network host --rm -w /data

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: recursive

      - name: Set up chart-testing
        run: |
          docker pull $CT_IMAGE

      - name: Find changes (PR)
        if: github.event_name == 'pull_request'
        run: |
          changed=$($DOCKER_COMMAND -v $(pwd):/data --user $(id -u) $CT_IMAGE ct list-changed --target-branch "$base_ref")
          if [[ -n "$changed" ]]; then
            echo "test_scope=--target-branch '$base_ref'" >> "$GITHUB_ENV"
          fi
        env:
          base_ref: ${{ github.base_ref }}

      - name: Find changes (push)
        if: github.event_name != 'pull_request'
        run: |
          echo "test_scope=--all" >> "$GITHUB_ENV"

      - name: Run chart-testing (lint)
        if: env.test_scope != ''
        run: |
          $DOCKER_COMMAND -v $(pwd):/data $CT_IMAGE \
              ct lint $test_scope --validate-maintainers=false --check-version-increment=false

      - name: Set up Helm
        if: env.test_scope != ''
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1

      - name: Create kind cluster
        if: env.test_scope != ''
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0

      - name: Run chart-testing (install)
        if: env.test_scope != ''
        run: |
          $DOCKER_COMMAND -v $(pwd):/data -v ~/.kube/config:/root/.kube/config:ro $CT_IMAGE \
              ct install $test_scope
